### ISSUE TITLE
Won't display /tags/ and /posts/

### ISSUE THREAD

**Issue by wooseopkim** [dldx/hpstr-hugo-theme#4]
While <https://dldx.github.io/tags/> and <https://dldx.github.io/posts/> works fine...

**[Edit]** I just figured out that `{{ else if .IsNode }}` block in `_defaults/terms.html` and `_defaults/list.html` was problem. Everything worked after I deleted it.

Thanks.

**Comment by dldx** [comment]
Hey @linterpreteur, it does work from my testing.. I'm not sure why you're having problems. On my test site, it is at https://dldx.github.io/hpstr-hugo-theme/posts/ and https://dldx.github.io/hpstr-hugo-theme/tags/

Could you tell me your config.yml? The problem is likely because of your settings for `relativeurls` and `baseurl`

**Comment by wooseopkim** [comment]
@dldx Ok, I'll try fixing my config, maybe in 3 hrs. I guess that might help.
